### ISSUE TITLE
support for \ at the end of a command

### ISSUE THREAD

**Issue by MarinPostma** [Abilbel/42sh#15]
\ at the end of a command should return a prompt as the command is unterminated

**Comment by cvignal** [comment]
```
echo "foo\
bar" | cat -e
```
does not display the right thing
It should be `foobar$` instead of
```
foo\$
bar$
```
`echo abc \| cat -e` the backslash should cancel the pipe
`echo "\\'abcd\\'"` there is two backslashes on each side of the abcd instead of one
`echo \'` should display in single quote
